### ISSUE TITLE
pylint failure with pylint 3.3.1

### ISSUE THREAD

**Issue by rfrancoise** [FoobarOy/foomuuri#49]
Debian upgraded pylint to version 3.3.1, which triggers this new warning and non-zero error code:

```
************* Module foomuuri
src/foomuuri:1277:0: R0917: Too many positional arguments (6/5) (too-many-positional-arguments)

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, -0.00)

zsh: exit 8     pylint src/foomuuri
```

Overriding this new warning will in turn generate a warning in pylint 3.2.x about the tag being unknown. Not sure what's the best way forward.

**Comment by suonpaa** [comment]
I cannot reproduce this with pylint 3.3.1 on my MacOs, nor with pylint 3.3.1 on my Debian either.

Also, as I see it, there's only four positional arguments here on line 1277:

`def rule_rate_log_policy(szone, dzone, rule, ipv, *, force_policy=None,
                         do_lograte=True):`

Which version of source code are you looking at? Guess this might already be fixed in this commit: https://github.com/FoobarOy/foomuuri/commit/875206b4439c5f4c03268f55a96318f12bbb1e4e.

**Comment by rfrancoise** [comment]
Sorry, I was referring to what's currently in Debian, i.e. the 0.25 release... and it didn't occur to me to check if it was already fixed. Thanks for pointing out the commit.
