### ISSUE TITLE
[Question] How to integrate with fail2ban?

### ISSUE THREAD

**Issue by ajayramaswamy** [FoobarOy/foomuuri#9]
make a separate table for fail2ban? in that case at what priority? or add hooks? or just dump the ip into a text file and make foomuuri read that?

**Comment by suonpaa** [comment]
I really do not undertand the necessity of integrating foomuuri with fail2ban. I am no expert, but I'd expect them to get along just fine even if they know nothing of each others business.

If I were to try, though, I'd try something along these lines on /etc/fail2ban/action.d/foomuuri.conf.

```
# Fail2Ban configuration file for Foomuuri
#
# Author: Samuli Suonpää <suonpaa@diurnalis.fi>
#
# More on Foomuuri: <https://github.com/FoobarOy/foomuuri>.
#

[Definition]
actionstart = 
actionstop = 
actioncheck = 
actionban = <nftables> add element inet <table> <addr_set> \{ <ip> \}
actionunban = <nftables> delete element inet <table> <addr_set> \{ <ip> \}
actionflush =

[Init]

nftables = nft
table = foomuuri
addr_set = fail2ban_4

[Init?family=inet6]
<addr_set> = fail2ban_6
```

This is doesn't really work, though, because iplist fail2ban will vanish if foomuuri is restarted, right? At that point fail2ban thinks ip's as still banned, which they are not, and will fail when trying to unban them.

Would it be impractical to make dynamic iplist persistent somehow, i.e. to be saved on firewall shutdown and reloaded on firewall start?

Also, how about implementing "add" and "del" to foomuuri iplist itself?

Something like this?
```
# foomuuri iplist add 1.2.3.4 dynamicblacklist
Address 1.2.3.4 added to iplist dynamicblacklist
# foomuuri iplist del 1.2.3.4 dynamicblacklist
Address 1.2.3.4 deleted from dynamicblacklist
# foomuuri iplist list dynamicblacklist
1.2.3.5
2.2.2.2
192.168.42.0/24
# echo Thanks! | mail -s "foomuuri iplist feature" <email_address_hidden>
```

This feature would make integration this easy:
```
actionban = foomuuri iplist add \{ <ip> \}
actionunban = foomuuri iplist del \{ <ip \}
```

AND this feature could be useful for many other scenarios too.

**Comment by kimheino** [comment]
> I really do not undertand the necessity of integrating foomuuri with fail2ban. I am no expert, but I'd expect them to get along just fine even if they know nothing of each others business.

Yes, that's true, and that's the best way.

> # foomuuri iplist add 1.2.3.4 dynamicblacklist
> # foomuuri iplist del 1.2.3.4 dynamicblacklist
> # foomuuri iplist list dynamicblacklist

This is a great idea. I'll reopen this issue.

**Comment by kimheino** [comment]
Following works with above commit:

foomuuri.conf:

```
iplist {
  @fail2ban
}

public-localhost {
  ssh saddr @fail2ban drop
}
```

Command line:

```
foomuuri iplist add @fail2ban 10.0.0.20 fd00:f00::20 10.1.2.0/24
foomuuri iplist del @fail2ban 10.0.0.21
foomuuri iplist list @fail2ban
```

Add will add new entry or refresh timeout for existing entry. Del works for unknown entry too.

Still in todo: Reboot or foomuuri restart clears entries.

**Comment by kimheino** [comment]
Entries are now saved for reboot/restart.

**Comment by Kirrus-Indiestone** [comment]
It might be worth copying / linking to / documenting the guide on setting up fail2ban here - it seems fairly comprehensive; https://blog.frehi.be/2023/10/29/setting-up-foomuuri-an-nftables-based-firewall/

**Comment by kimheino** [comment]
See also new build-in fail2ban alike feature:

https://foomuuri.foobar.fi/development/example/advanced/#automatic-ip-address-banning

**Comment by Kirrus-Indiestone** [comment]
Interesting, and potentially a decent response to basic DoS attacks, but lack of log parsing does leave it less flexible than fail2ban, denyhosts etc. Automatically expiring blocks is useful when a user has locked themselves out accidentally
